### PR TITLE
add CAM Simulator

### PR DESCRIPTION
**Pull request by roberto-arista**
😎

### CODE REVIEW

**Comment by typemytype** [comment]
could you point to the file directly not the the github html page

icon --> https://raw.githubusercontent.com/roberto-arista/cam-simulator/main/CAMSimulatorMechanicIcon.png
info path --> https://raw.githubusercontent.com/roberto-arista/cam-simulator/main/build/CAMSimulator.roboFontExt/info.plist

for github Mechanic can find the infoPath and zipPath, they are not required

**Comment by roberto-arista** [comment]
so I need to fix the icon and then I can remove the info path?

**Comment by roberto-arista** [comment]
it would then result this:

```yaml
extensionName: CAM Simulator
repository: https://github.com/roberto-arista/cam-simulator
extensionPath: build/CAMSimulator.roboFontExt
description: Visualize CNC limitations right in the glyph editor
developer: Roberto Arista
developerURL: https://github.com/roberto-arista
tags: [ contours drawing ]
icon: https://raw.githubusercontent.com//roberto-arista/cam-simulator/raw/master/CAMSimulatorMechanicIcon.png
```

**Comment by typemytype** [comment]
perfect! thanks

**Pull request merged**
