### PR TITLE
stemPlow.yml data entry

### PR DESCRIPTION
**Pull request by RafalBuchner**

### CODE REVIEW

**Comment by typemytype** [comment]
the icon path is not correct, should be:
`https://raw.githubusercontent.com/rafalbuchner/StemPlow/master/images/StemPlow-icon.png`

**Comment by RafalBuchner** [comment]
I think it should be ok now

**Comment by RafalBuchner** [comment]
@typemytype let me know if there is something, I should still fix

**Comment by typemytype** [comment]
all fine now! thanks

**Pull request merged**
