### PR TITLE
Add mark tool extension.

### PR DESCRIPTION
**Pull request by typoman**

### CODE REVIEW

**Comment by gferreira** [comment]
hello @bahman,

because your extension is hosted on GitLab, the URLs to icon, zip and info files need to follow a different pattern. I’ve made some tests, this works:

```yaml
extensionName: Mark Tool
repository: https://gitlab.com/typoman/robofont-mark-tool
extensionPath: build/RoboFontMarkTool.roboFontExt
description: A tool to adjust mark positioning in the glyph view.
developer: Bahman Eslami
developerURL: http://bahman.design
tags: [ mark, positioning, tool ]
infoPath: https://gitlab.com/api/v4/projects/15840327/repository/files/RoboFontMarkTool.roboFontExt%2Finfo.plist/raw?ref=master
zipPath: https://gitlab.com/api/v4/projects/15840327/repository/archive.zip?sha=master
icon: https://gitlab.com/api/v4/projects/15840327/repository/files/robofontMarkToolExtensionMechanicIcon.png/raw?ref=master
dateAdded: 2020-01-07 10:10:10
```

the zip currently has 45.5MB (!!), so it takes a while to download. you don’t need to include a zip in the repository, GitHub / GitLab creates it automatically. the gif videos are also quite heavy.

**Comment by typoman** [comment]
Thank you Gustavo, sorry I about the broken links, I should have tested them. For now I need to commit the changes you made to make this work?

**Comment by typoman** [comment]
I removed the zip file. I can remove the GIF files and reference them from the repo I guess to make it less heavy?

**Comment by gferreira** [comment]
yeah, hotlinking the gifs instead of including them in the extension is a good idea. will make the mechanic experience faster.

**Comment by gferreira** [comment]
hi @typoman,

is this ready for merging?

**Comment by typoman** [comment]
Hey Gustavo, I made some changes and it was unfinished that's why I haven't said anything. I will make a build and let you know. Thank you!

**Comment by typoman** [comment]
I added the missing features and now it's ready to merge. Hope it everything works fine.

**Pull request merged**
