### PR TITLE
add mm2SpaceCenter

### PR DESCRIPTION
**Pull request by cjdunn**

### CODE REVIEW

**Comment by typemytype** [comment]
super!!

**Comment by cjdunn** [comment]
@typemytype hmm, when I try to install via Mechanic2 I get "Hash does not match." in my output window and it doesn't install. Any ideas what's wrong? Thanks!!

**Comment by gferreira** [comment]
@cjdunn the hash file is created for trial extensions only. my guess is that the extension code was modified after the hash was created, so there’s a mismatch. (or maybe you are 1+ year in the future :)

the hash needs to be generated again… are you building the extension with a script?

**Comment by cjdunn** [comment]
@gferreira yes, I'm using a script. I have the script and source files included on the branch  next-master:
https://github.com/cjdunn/MM2SpaceCenter/tree/next-master

which I was planning to move to master soon. Would you mind trying to build from that branch and let me know if you see what could be causing the issue? Thanks so much

**Comment by gferreira** [comment]
hello @cjdunn,

I’ve just submitted a [pull request] with a few changes, it is now working fine as far as I can test.

I’m a bit puzzled about why the extension is built as trial and binary, while the source code is available – is in intentional? (you write that pull requests are appreciated, so I suspect not)

[pull request]: https://github.com/cjdunn/MM2SpaceCenter/pull/2

**Pull request merged**
